version: '3'
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
services:
  servicio1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8204:80"
    volumes:
      - C:\Users\brian\OneDrive\Documentos\Contenedores\BryanRestrepo-2503285\datadrive:/datadrive
    networks:
      - mynetwork
  servicio2:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    networks:
      - mynetwork